version: 105.0.1.{build}
image: Visual Studio 2017

build_script:
  - build.bat

skip_tags: true

-
  branches:
    only:
      - master

  artifacts:
    path: 'RestSharp\bin\Release\*.nupkg'

  configuration: Release

-
  branches:
    only:
      - develop

  artifacts:
    path: 'RestSharp\bin\Debug\*.nupkg'

  configuration: Debug

-
  configuration: Debug