version: 105.0.1.{build}
image: Visual Studio 2017

build_script:
  - build.bat

skip_tags: true

- provider: Slack
  incoming_webhook:
    secure: oYYkGVXbEgGf60T2CM6XlyG31S89BCgspVL9zoBwJVf1EPVJxv55BSqXQOTOyYRCWQC7mzjT2Gc1i2ujoJeq9rMPIYjxjDr8XJvFp8+/5rs= 

-
  branches:
    only:
      - master

  artifacts:
    path: 'RestSharp\bin\Release\*.nupkg'

  configuration: Release

-
  branches:
    only:
      - develop

  artifacts:
    path: 'RestSharp\bin\Debug\*.nupkg'

  configuration: Debug

-
  configuration: Debug