-
  branches:
    only:
      - master

  artifacts:
    path: 'RestSharp\bin\Release\*.nupkg'

  configuration: Release

  image: Visual Studio 2019

  build_script:
    - build.bat

  skip_tags: true
  test: off
-
  branches:
    only:
      - develop

  artifacts:
    path: 'RestSharp\bin\Debug\*.nupkg'

  configuration: Debug

  image: Visual Studio 2019

  build_script:
    - build.bat

  skip_tags: true
-
  configuration: Debug

  image: Visual Studio 2019

  build_script:
    - build.bat

  skip_tags: true
  test: off

