name: Publish the docs

on:
  push:
    paths:
      - 'docs/**'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/publish-docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          persist_credentials: false
      
      - name: Vuepress
        run: |
          yarn install
          yarn docs:build
          
      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'docs/.vuepress/dist'
          CLEAN: true
