name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
          
      - name: Run tests netcoreapp3.1
        run: dotnet test -c Release -f netcoreapp3.1

      - name: Run tests net461
        run: dotnet test -c Release -f net461
        
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Vuepress
        run: |
          yarn install
          yarn docs:build
